### ISSUE TITLE
New url https://freekassa.ru

### ISSUE THREAD

**Issue by nicdnepr** [Churakovmike/yii2-free-kassa#1]
Freekassa has changed api url https://docs.freekassa.ru/
Will you do updates to package?

**Comment by Churakovmike** [comment]
Hey! Perhaps in the near future. If you need it very urgently, you can issue a merge request.

**Comment by nicdnepr** [comment]
Yes I need it, but I don't have any merge
Near future is  how close?

**Comment by Churakovmike** [comment]
I just looked at the new api and I see that simply changing the url will not work. Now there is a completely different api with which this package does not work.
The api version supported by the package is located here https://www.free-kassa.ru/docs/api.php
